apiVersion: apps/v1
kind: Deployment
metadata:
  name: helados-app
spec:
  selector:
    matchLabels:
      app: helados
  replicas: 3
  template:
    metadata:
      labels:
        app: helados
    spec:
      containers:
      - name: icecream-api
        image: agl983/buildassembly:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: helados-app-service
spec:
  selector:
    app: helados
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 80  
  type: NodePort  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helados-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.agonzalezlopez.com  # Reemplaza con tu propio dominio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helados-app-service
            port:
              number: 80

